name: SomePlugin
main: net.apherfox.someplugin.SomePlugin
version: 1.2
authors: [ApherFox /*main author of the plugin*/, 
Creepinson /*author of template https://github.com/creepinson/SpigotPluginTemplate*/]
commands:
  some:
    description: Some command 'shrugs'
  leash:
    description: View a leash request
    usage: /leash (id)
  unleash:
    description: Unleash yourself of a submissive
    
permissions:
